name: 'Push Email Notification Action'
description: 'Notifies email receiptients of a push of secure file'
branding:
  color: 'green'
  icon: 'mail'
inputs:
  fromMailAddress:
    description: 'Email from address'
    required: true
    default: 'no-reply@example.com'
  toMailAddress:
    description: 'Semi-colon separated list of email address recipients'
    required: true
  subjectPrefix:
    description: 'Prefix in the subject line'
    required: false
    default: '__NONCE__'
  verbose:
    description: 'Turn on verbose logging'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
